import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-zinc-950 text-white font-mono antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-1">
          {children}
        </main>

        <footer className="text-center py-6 text-zinc-400 text-base">
          Built with ❤️ by{" "}
          <a
            href="https://github.com/zasumean"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-white"
          >
            @zasumean
          </a>
        </footer>
      </body>
    </html>
  );
}

